openapi: 3.0.3
info:
  title: Simple API
  description: A basic OpenAPI spec for importing into Gravitee.
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /hello:
    get:
      summary: Greet the user
      operationId: getHello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
